spring:
  config:
    activate:
      on-profile: local

  ## DataBase (Redis)
  cache:
    type: redis
    redis:
      #      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379

  ## DataBase (MySQL)
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Kakao login
kakao:
  client:
    id: 4f04a12471c811be6b57fd31096dacdf
    secret: mK84AIu4fi5yRKyw0aXjHNWGiEKJxqnz
    scope:
      - account_email
      - profile_nickname
    grant-type: authorization_code
    redirect-uri: http://localhost:8080/api/v1/kakao/login

  provider:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    user-name-attribute: id

jwt:
  secret: 234ewr
  token:
    access-expiration: 43200000 # 12시간
    refresh-expiration: 604800000 # 7일