spring:
  config:
    activate:
      on-profile: local

  ## DataBase (Redis)
  cache:
    type: redis
    redis:
      #      cache-null-values: true # null 캐싱 여부
      host: localhost
      port: 6379

  ## DataBase (MySQL)
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  ## JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true